In [12]:
import numpy as np
arr = np.array([1,2,3,4])
arr
list1 = [2,3,4,5]
print(arr, list1)
arr2 = np.array([1,2,3,4], dtype=np.float64)
print(arr2.dtype, arr2.shape, arr2.size, arr2)

[1 2 3 4] [2, 3, 4, 5]
float64 (4,) 4 [1. 2. 3. 4.]


In [24]:
arr2 = np.array(['2','3','4','5'], dtype=np.string_)
arr2.astype(float)
arr3 = np.arange(5)
arr3
arr4 = np.empty(8, dtype='u4')
#arr4.shape

In [39]:
arr5 = np.array([[1,2,3],[4,5,6]], dtype=np.float64)
arr5.shape
arr6 = np.array([[1,2], [3,4], [5,6]], dtype=np.int32)
# y = 2x + 1
arr6 * 2
arr6 * arr6 * arr6
arr6 / 2
arr6 > 0

array([[ True,  True],
       [ True,  True],
       [ True,  True]])

In [68]:
arr7 = np.arange(10)
arr7[1]
arr7[0]
arr7[:2]
# 0  1  2
#   0  1
arr7[5:8]
arr8 = np.array([[1,2],[3,4],[5,6]])
arr8.dtype
arr8.shape
arr8[0][0]
arr8[2][0]
arr8[2,0]

list2 = [[1,2],[3,4],[5,6]]
list2[0][1]
list3 = [[[1,2,3], [4,5,6]],[[7,8,9],[10, 11, 12]]]
list3[0][0][0]
arr9 = np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10, 11, 12]]])
arr9.shape
arr9.ndim
arr9[0][0][0] = 100
arr9

array([[[100,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]]])

In [112]:
arr10 = np.empty((8,4))
for i in range(8):
    arr10[i] = i
#arr10.shape, arr10.ndim
arr10
arr10[[0,1,2]]
arr10[[-1, -3]]
arr11 = np.arange(10)
arr11
arr11.reshape(2,5)
arr12 = np.arange(32).reshape(8,4)
arr12[[1,5,2,7],[0,3,1,2]]
arr13 = arr12[[1,5,7,2]][:, [0,3,1,2]]
arr13.shape

(4, 4)

In [124]:
arr14 = np.arange(20).reshape(5,4)
arr14.shape
print(arr14)
arr15 = arr14.T
arr15.shape

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


(4, 5)

In [130]:
a = np.array([[1,2], [3,4]])
b = np.array([[1,2], [3,4]])
#1,2  1,2
#3,4  3,4
c = np.dot(a, b)

In [156]:
a1 = np.arange(4).reshape(2,2)
a1
#a1.T
np.transpose(a1,(0,1))

a2 = np.arange(10).reshape(2,5)
# a2.T
a3 = np.transpose(a2, (1,0))
a3.shape
# 0 => 1차원, 1 => 2차원
# 0 => 3차원, 1 => 2차원, 2 => 1차원
# a2.swapaxes(0,1)


array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [164]:
a10 = np.array([[1,2,3,4], [2,4,6,8], [10,20,30,40]])
a10.shape
a11 = np.array([2,4,6,8])
print(a10.shape, a11.shape)
a12 = a10 + a11
a12.shape
a13 = np.array([1,2,3,4])
a14 = np.array([1,2,3,4,5])
a15 = a13 + a14

(3, 4) (4,)


ValueError: operands could not be broadcast together with shapes (4,) (5,) 