In [7]:
inputs = [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]]
        
weights = [
    [1,2,3,4],
    [2,3,4,4],
    [1,2,3,4]
]
biases = [2,2,3]
np.dot(weights, inputs) + biases
# import numpy as np
# a = [1,2,3]
# b = [1,2,3]
# np.dot(a, b) # 1*1 + 2*2 + 3*3
# a1 = np.array(a)
# b1 = np.array(b)
# a1, b1, a1.shape, b1.shape
# np.dot(a1, b1.T)

array([32, 38, 33])

In [11]:
a = [1,2,3]
b = [3,4,5]
a1 = np.array([a])
b1 = np.array([b])
a1, b1, a1.shape, b1.shape
np.dot(a1, b1.T)

array([[26]])

In [20]:
inputs = [[1,2,3,4],
        [1,2,3,4],
        [1,2,3,4]]        
weights = [
    [1,2,3,4],
    [2,3,4,4],
    [1,2,3,4]
]
biases = [2,2,3]
a3 = np.array(inputs)
b3 = np.array(weights)
a3.shape, b3.shape, b3.T.shape
# output = np.dot(a3, b3.T) + biases
# output.shape

((3, 4), (3, 4), (4, 3))

In [22]:
inputs = [[1,2,3,4],[1,2,3,4],[1,2,3,4]]  
weights = [[1,2,3,4],[2,3,4,4],[1,2,3,4]]  
biases = [2,2,3]
weights2 = [[1,2,3],[2,3,4],[1,2,3]]  
biases2 = [2,2,3]

layer1_outputs = np.dot(inputs, np.array(weights).T) + biases
layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2
layer2_outputs

array([[209, 312, 210],
       [209, 312, 210],
       [209, 312, 210]])